// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVoL2n3t7Wlxq_a4cDU9W0_aYuaLLIdME',
    appId: '1:982977699496:web:30d6f3474b299571bfec9d',
    messagingSenderId: '982977699496',
    projectId: 'donnavita-cc447',
    authDomain: 'donnavita-cc447.firebaseapp.com',
    storageBucket: 'donnavita-cc447.appspot.com',
    measurementId: 'G-QZ3GWHM1EZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgmkqQnoRMFJDCyNf1zvoBRLCEWPc9pa4',
    appId: '1:982977699496:android:89cf3790659e3621bfec9d',
    messagingSenderId: '982977699496',
    projectId: 'donnavita-cc447',
    storageBucket: 'donnavita-cc447.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkNjejqBEjMBPk0SvXliDHyEf48AjPBI0',
    appId: '1:982977699496:ios:dac6a1a18cc61aafbfec9d',
    messagingSenderId: '982977699496',
    projectId: 'donnavita-cc447',
    storageBucket: 'donnavita-cc447.appspot.com',
    iosClientId: '982977699496-vrm9s45m4uji4612t15jp34d9366dos7.apps.googleusercontent.com',
    iosBundleId: 'com.example.secondapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkNjejqBEjMBPk0SvXliDHyEf48AjPBI0',
    appId: '1:982977699496:ios:dac6a1a18cc61aafbfec9d',
    messagingSenderId: '982977699496',
    projectId: 'donnavita-cc447',
    storageBucket: 'donnavita-cc447.appspot.com',
    iosClientId: '982977699496-vrm9s45m4uji4612t15jp34d9366dos7.apps.googleusercontent.com',
    iosBundleId: 'com.example.secondapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVoL2n3t7Wlxq_a4cDU9W0_aYuaLLIdME',
    appId: '1:982977699496:web:6e35cad46133ab4ebfec9d',
    messagingSenderId: '982977699496',
    projectId: 'donnavita-cc447',
    authDomain: 'donnavita-cc447.firebaseapp.com',
    storageBucket: 'donnavita-cc447.appspot.com',
    measurementId: 'G-DB33T718JZ',
  );
}
